# Generated by Django 5.0.6 on 2024-06-19 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название курса"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="превью"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="описание курса",
                    ),
                ),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="название урока"),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="превью"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="описание курса",
                    ),
                ),
                ("url", models.CharField(max_length=50, verbose_name="ссылка")),
            ],
            options={
                "verbose_name": "урок",
                "verbose_name_plural": "уроки",
            },
        ),
    ]
